targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '.mem.g.dart': '.mem.g.dart'
      dart_mem_annotation_generator|dart_mem_annotation_builder:
        enabled: true
      dart_mem_annotation_generator|dart_mem_code_generator:
        enabled: true


builders:

  # Annotation Builder
  dart_mem_annotation_builder:
    import: "package:dart_mem_annotation_generator/builder.dart"
    builder_factories: [ "annotationBuilder" ]
    build_extensions: { '.dart': [ '.mem.g.dart' ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "dart_mem_annotation_generator|dart_mem_code_generator" ]
    runs_before:
      - dart_mem_annotation_generator|dart_mem_code_generator

  # Code Generator
  dart_mem_code_generator:
    import: "package:dart_mem_annotation_generator/builder.dart"
    builder_factories: [ "codeGenerator" ]
    build_extensions: { '.mem.g.dart': [ '.mem.dart' ] }
    auto_apply: dependents
    build_to: source
#    applies_builders: [ "source_gen|combining_builder" ]
#    applies_builders: [ "json_serializable|json_serializable" ]
    runs_before:
      - json_serializable|json_serializable
      - source_gen|combining_builder
