targets:
  $default:
    builders:
      dart_mem_annotation_generator|dart_mem_annotation_builder:
        enabled: true

builders:

  # Annotation Builder
  dart_mem_annotation_builder:
    import: "package:dart_mem_annotation_generator/builder.dart"
    builder_factories: [ "annotationBuilder" ]
    build_extensions: { '.dart': [ '.mem.dart' ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "freezed" ]
    runs_before:
      - json_serializable|json_serializable
      - freezed
