targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '{{}}.mem.g.dart': '{{}}.mem.dart'
      dart_mem_annotation_generator|dart_mem_annotation_builder:
        enabled: true
      dart_mem_annotation_generator|dart_mem_code_generator:
        enabled: true


builders:

  # Annotation Builder
  dart_mem_annotation_builder:
    import: "package:dart_mem_annotation_generator/builder.dart"
    builder_factories: [ "annotationBuilder" ]
    build_extensions: { '{{}}.dart': [ '{{}}.g.dart' ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "dart_mem_annotation_generator|dart_mem_code_generator" ]
    runs_before:
      - dart_mem_annotation_generator|dart_mem_code_generator
      - source_gen|combining_builder

  # Code Generator
  dart_mem_code_generator:
    import: "package:dart_mem_annotation_generator/builder.dart"
    builder_factories: [ "codeGenerator" ]
    build_extensions: { '{{}}.g.dart': [ '{{}}.mem.dart' ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
    runs_before:
      - source_gen|combining_builder