name: example_for_dart_mem_annotation
description: A project used to demo the DartModelEntityAnnotationGenerator
version: 0.0.2
homepage: https://www.linkedin.com/in/resam/
repository: https://github.com/reesaam/dart_mem_annotation_generator.git

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  dart_mem_annotation:
    path: ../../annotation/

dev_dependencies:
  build_runner: ^2.4.13
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  dartdoc: ^8.0.8
  lints: ^4.0.0
  test: ^1.24.0
  dart_mem_annotation_generator:
    path: ../../generator/