// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sample_inner_inner_class.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Mem Generator
///   [InnerInnerSample] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: InnerInnerSample
///     Constructors Count: 1
///     Variables Count: 3

///   ==> Model Class:

@Freezed(toJson: true, fromJson: true)
class InnerInnerSampleModel with _$InnerInnerSampleModel {
  const factory InnerInnerSampleModel({
    final String? name,
    final String? description,
    final String? longDescription,
  }) = _InnerInnerSampleModel;

  factory InnerInnerSampleModel.fromJson(Map<String, dynamic> json) =>
      _$InnerInnerSampleModelFromJson(json);
}

///   ==> Entity Class:

@Freezed(toJson: false, fromJson: false)
class InnerInnerSampleEntity with _$InnerInnerSampleEntity {
  const factory InnerInnerSampleEntity({
    final String? name,
    final String? description,
    final String? longDescription,
  }) = _InnerInnerSampleEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnInnerInnerSampleEntity on InnerInnerSampleEntity {
  InnerInnerSampleModel get mapper => InnerInnerSampleModel(
        name: name,
        description: description,
        longDescription: longDescription,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnInnerInnerSampleModel on InnerInnerSampleModel {
  InnerInnerSampleEntity get mapper => InnerInnerSampleEntity(
        name: name,
        description: description,
        longDescription: longDescription,
      );
}
