name: dart_mem_annotation
description: A Code Generator Plugin to Generate Models, Entities and Mappers base on Annotation.
version: 0.0.2
homepage: https://www.resam.site
repository: https://github.com/reesaam/dart_mem_annotation_generator.git
funding:
  - https://resam.site

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.3

dependencies:
  build_runner: ^2.4.13
  dartdoc: ^8.0.8

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  dart_mem_annotation_generator:
    path: ../generator/